const errorConstants = Object.freeze({
  ACCESS_DENIED: "Access denied",
  ACCOUNT_BLOCKED: "Account is blocked",
  ACCOUNT_INACTIVE: "Account is inactive",
  USER_NOT_FOUND: "User not found",
  ALREADY_EXISTS: "Already exists",
  DATABASE_URL_REQUIRED: "DATABASE_URL is required",
  DOCUMENT_NOT_FOUND: "Document not found",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  EMAIL_NOT_CONFIGURED: "Email service is not configured",
  INVALID_CREDENTIALS: "Invalid email or password",
  INVALID_OTP: "Invalid OTP",
  INVALID_REFRESH_TOKEN: "Invalid refresh token",
  INVALID_REQUEST: "Invalid request",
  INVALID_SESSION_ID: "Invalid session id",
  INVALID_USER_ID: "Invalid user id",
  INVALID_TOKEN: "Invalid token",
  MISSING_AUTH_HEADER: "Authorization header is required",
  NOT_FOUND: "Not found",
  NOTIFICATION_NOT_FOUND: "Notification not found",
  OTP_EXPIRED: "OTP is expired",
  OTP_NOT_VERIFIED: "OTP is not verified",
  PATIENT_NOT_FOUND: "Patient not found",
  RATE_LIMIT_EXCEEDED: "Too many requests, please try again later",
  ROUTE_NOT_FOUND: "Route not found",
  SESSION_NOT_FOUND: "Session not found",
  SOMETHING_WENT_WRONG: "Something went wrong, please try again later",
  UNAUTHORIZED: "Unauthorized",
  VALIDATION_FAILED: "Validation failed",
  USER_NAME_INVALID: "User name can only contain alphanumeric characters",

  DATE_OF_BIRTH_REQUIRED: "Date of birth is required",
  EMAIL_REQUIRED: "Email is required",
  EMAIL_TOO_LONG: "Email is too long",
  EMAIL_TOO_SHORT: "Email must be at least 8 characters",
  FILE_SIZE_INVALID: "File size must be a positive number no larger than 25MB",
  FILE_TYPE_INVALID: "Please enter a valid file type",
  FULL_NAME_REQUIRED: "Full name is required",
  FIRST_NAME_REQUIRED: "First name is required",
  LAST_NAME_REQUIRED: "Last name is required",
  GENDER_INVALID: "Enter a valid gender",
  HOSPITAL_NAME_REQUIRED: "Hospital name is required",
  ID_INVALID: "Id must be a valid UUID",
  NAME_TOO_LONG: "Name is too long",
  NAME_TOO_SHORT: "Name is too short",
  ONLY_ALPHABETS: "Only alphabets are allowed",
  PASSWORD_REQUIRED: "Password is required",
  PASSWORD_TOO_LONG: "Password is too long",
  PASSWORD_TOO_SHORT: "Password must be at least 8 characters",
  PASSWORD_UPPERCASE_REQUIRED: "Password must contain an uppercase letter",
  PASSWORD_LOWERCASE_REQUIRED: "Password must contain a lowercase letter",
  PASSWORD_NUMBER_REQUIRED: "Password must contain a number",
  PASSWORD_SYMBOL_REQUIRED: "Password must contain a special character",
  PHONE_INVALID: "Phone must contain exactly 10 digits",
  PHONE_REQUIRED: "Phone number is required",
  REFRESH_TOKEN_REQUIRED: "Refresh token is required",
  USER_NAME_REQUIRED: "User name is required",
  VALID_DOCUMENT_TYPE_REQUIRED: "Please enter a valid document type",
  VALID_EMAIL_REQUIRED: "Please enter a valid email",
});

module.exports = { errorConstants };
