const messageConstant = {
  // RESPONSE
  SUCCESS: "Success",
  ERROR: "Error",
  OK: "OK",
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  DELETED: "DELETED",
  NO_DATA_FOUND: "No data found",
  SOMETHING_WENT_WRONG: "Something went wrong, please try again later",

  // USER
  USER_ADDED_SUCCESSFULLY: "User Added Successfully",
  USER_LOGIN_SUCCESSFULLY: "User Login Successfully",
  USERID_REQUIRED: "UserId is required",
  USER_UPDATED_SUCCESSFULLY: "User Updated Successfully",
  USER_DELETED_SUCCESSFULLY: "User Deleted Successfully",
  USERS_FOUND_SUCCESSFULLY: "User Found Successfully",
  LOGIN_SUCCESSFULLY: "Login Successfully",
  USER_LOGIN_SUCCESSFULLY: "User Login Successfully",
  OTP_VERIFIED: "OTP is verified",
  USER_BLOCKED: "User Blocked",
  EMAIL_VERIFY_SUCCESSFULLY: "Email is verified successfully",
  EMAIL_ALREADY_EXISTS: "Email is already exists",
  USER_PERMANENTLY_DELETED_SUCCESSFULLY: "User Permanently Deleted Successfully",
  USER_FETCHED_SUCCESSFULLY: "User Fetched Successfully",
  USER_LIST_FETCHED_SUCCESSFULLY: "User List Fetched Successfully",

  //EXCEPTION
  INVALID_SESSIONID:"Invalid session id",
  SESSION_NOT_FOUND: "Session not found",
  LOGOUT_SUCCESS: "Logout successfully",
  ALREADY_LOGOUT: "Already logout",
  INVALID_TOKEN:"Invalid token",
  VALIDATION_FAILED:"Validation failed",
  INVALID_REQUEST: "Invalid request",
  ALREADY_EXIST:"Already exist",
  NOT_FOUND: "Not found",
  USER_NOT_FOUND: "user not found",
  UNAUTHORIZED: "Unauthorized",
  INTERNAL_SERVER_ERROR: "Internal server error",
  USER_DOES_NOT_EXIST_WITH_THIS_EMAIL: "User does not exist with this email",
  INCORRECT_PASSWORD: (remainingAttemptCount) =>
    `Incorrect password ${remainingAttemptCount} attempts remaining.`,
  EMAIL_PASSWORD_REQUIRED: "Email & Passwrod are required",
  USER_ALREADY_EXISTS_WITH_THIS_EMAIL: "User already exists with this email",
  TOO_MANY_ATTEMPTS: "Too many failed attempts. Your account has been BLOCKED.",
  INVALID_EXPIRE_OTP: "Invalid Or Expired OTP",

  //VALIDATIORS
  VALID_EMAIL: "Please enter valid email",
  ENTER_VALID_GENDER:"Enter a valid gender",
  HSP_NAME_REQUIRE:"Hospital name is required",
  VALID_FILE_SIZE:"File size exceeds the 25MB limit. Please upload a smaller file.",
  ENTER_VALID_FILETYPE:"Please enter a valid file ",
  VALID_DOCUMENT:"Please enter valid document type",
  EMAIL_REQUIRED: "Please Enter Email",
  EMAIL_TOO_SHORT: "Email must be atleast 5 character",
  EMAIL_TOO_LONG: "Email is too long",
  PASSWORD_REQUIRED: "Enter Password",
  PASSWORD_TOO_SHORT: "Password must be atleast 8 characters",
  PASSWORD_TOO_LONG: "Password is too long",
  NAME_REQUIRED: "Enter Name",
  NAME_TOO_SHORT: "Name is too short",
  NAME_TOO_LONG: "Name is too long ",
  PHONE_NUMBER_REQUIRED: "Enter phone number",
  PHONE_NUMBER_MUST_BE_10_DIGITS: "Enter only 10 digit number",
  PASS_TOO_LONG: "Password is too long",
  NO_ALFABATES: "No alphabates are allowed",
  AGE_GREATER_0: "Age must be greater than zero",
  MUSTCONTAIN_LOWERCASE: "Name must write in lowercase letter",
  NOT_ELIGIBLE: "Not eligible for login",
  INVALID_ZIP: "Invalid zipCode",
  MUST_UPPER: "Must contain uppercase",
  MUST_LOWER: "Must contain lowercase",
  MUST_NUM: "Must contain number",
  MUST_SYMBOL: "Must contain special character",
  ONLY_ALPHABETS: "only alphabets are allowed",
};
module.exports = messageConstant;
